spring:
  profiles:
    group:
      dev: dev, common, key
      prod: prod, common, key
---
spring:
  config:
    activate:
      on-profile: common
  name: spring_remind
  messages:
    basename: i18n/exception
    encoding: UTF-8
  freemarker:
    template-loader-path=classpath: /templates
    suffix: .ftl
springdoc:
  pathsToMatch: /v1/**
  api-docs:
    path: /docs
  swagger-ui: