spring:
  profiles:
    active: key
  application:
  name: spring_remind
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: create
    showSql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  freemarker:
    template-loader-path=classpath: /templates
    suffix: .ftl
  url:
    base: http://localhost:8080
springdoc:
  pathsToMatch: /v1/**
  api-docs:
    path: /docs
  swagger-ui: