services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  db:
    image: oscarfonts/h2:latest
    restart: always
    environment:
      H2_OPTIONS: -ifNotExists
    ports:
      - "1521:1521"
      - "8081:81"
    volumes:
      - /docker/volumes/h2:/opt/h2-data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:tcp://proj-db-1:1521/test"
    volumes:
      - ./:/app/