networks:
  backend-net:
    external: true
services:
  nginx:
    image: nginx:latest
    networks:
      - backend-net
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf-available:/etc/nginx/conf-available