x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/app/

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf-available:/etc/nginx/conf-available
    depends_on:
      - app-blue
  db:
    image: oscarfonts/h2:latest
    restart: always
    environment:
      H2_OPTIONS: -ifNotExists
    ports:
      - "1521:1521"
      - "8081:81"
    volumes:
      - /docker/volumes/h2:/opt/h2-data

  app-blue:
    expose:
      - 8000
    <<: *app
    container_name: app-blue
    environment:
      SERVER_PORT: "8000"
      SPRING_DATASOURCE_URL: "jdbc:h2:tcp://proj-db-1:1521/test"

  app-green:
    expose:
      - 8001
    <<: *app
    container_name: app-green
    environment:
      SERVER_PORT: "8001"
      SPRING_DATASOURCE_URL: "jdbc:h2:tcp://proj-db-1:1521/test"
